### ISSUE TITLE
[Bug]: AutoBattle Crashing game

### ISSUE THREAD

**Issue by IcyWhisper** [Charismara/pixelmon-hacks-issues#1]
### Minecraft Version

1.12.2

### Forge Version

36.2.39

### Pixelmon Version

8.4.2

### Journeymap Version

5.7.1

### Pixelmon Hacks Version

1.0.0.10

### Describe the bug

I am using tyranitar and whenever my tyranitar runs out of PP or otherwise only has "struggle" as the only move, the auto battle crashes. On top of this.

### To Reproduce

1. Auto battle
2. Run out of PP or only have move "struggle"
3. crash

**Comment by Charismara** [comment]
Thank you for Reporting the Crash.

I am sorry to tell you that the MC 1.12.2 version of Pixelmon Hacks isn't supported anymore. Is this still an Issue with the latest 1.16.5 Version?

**Comment by IcyWhisper** [comment]
Hello,
I cannot confirm whether or not this issue is present in 1.16.2 since I only play on modpacks like pixelmon+ on technic or pixelmon reforged on curseforge which both use 1.12.2

**Comment by Charismara** [comment]
I am closing this issue as version 1.12.2 is no longer supported. I recommend you try the [Official Pixelmon Modpack](https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack) for 1.16.5.
