### ISSUE TITLE
[Feature Request]: Alter Form Finder

### ISSUE THREAD

**Issue by Trixfinity** [Charismara/pixelmon-hacks-issues#10]
### Describe the Feature

Thanks for adding the Ultra Beast Finder, I really do appreciate the work you do (I use this in all my worlds)

Sorry If I seem nit-picky, but I am trying to do the Galaxian Articuno quest and It needs to find multiple Altered Pokemon to defeat for a chance for Articuno to spawn.

Same as All the other Pokemon Finders, but only pings for Alter versions of the Pokemon.

**Comment by Charismara** [comment]
Could u explain that a bit more? What exactly is it that you need?

**Comment by Trixfinity** [comment]
To ping all Altered Form Pokemon surrounding you, just like the Legendary Finder and Ultra Beast Finder.

In order to spawn Galarian Articuno, you need to defeat a certain amount of Altered Form Pokemon. That's what I meant by this Request

**Comment by Charismara** [comment]
Are you talking about those?

![image](https://user-images.githubusercontent.com/14293974/214007838-039b0674-6986-4cf0-bf29-413f74bbcaea.png)

**Comment by Noeble** [comment]
and galarian moltres need ashen and galarian zapdos need strike, both are special texture

**Comment by Trixfinity** [comment]
> Are you talking about those?
> 
> ![image](https://user-images.githubusercontent.com/14293974/214007838-039b0674-6986-4cf0-bf29-413f74bbcaea.png)

Yes, that's the Pokemon that I was talking about

**Comment by Trixfinity** [comment]
And yes, for all the Galarian Legendary birds, You would need a Ashen Finder, Strike Finder, and a Alter Finder

**Comment by Charismara** [comment]
i'm gonna take a look what's possible :)

**Comment by Charismara** [comment]
done with `#find` in 2.1.13.0

**Comment by JasonCastle** [comment]
Can't seem to get alternate forms to work; I can't figure out the correct syntax. Can you be more specific for how to use the command? example: " #find add Onix Crystal " doesn't work at all, its just red. I'm seeing other players on Curseforge ask how to use the command properly as well.
