### ISSUE TITLE
[Question]:  Catch Series commands and range

### ISSUE THREAD

**Issue by Ukrayina** [Charismara/pixelmon-hacks-issues#13]
### Describe the Feature

One really useful update that I think would improve this mod a lot is making catchSeries command work for multiple pokemon instead of only one at a time. 
Example: 
#catchSeries add dratini
#catchSeries add beldum
#catchSeries start
The mod should search for both dratini and beldum.

Some other useful commands:
#catchSeries stop (stops without removing the pokemon from the array)
#catchSeries clear (clears the array of pokemon and stops)
#catchSeries remove <pokemon_name> (removes the given pokemon from the array)
#catchSeries list (shows all the pokemon in catchSeries array)

Also, why only 32x32x32 instead of looping all the loaded entities? Is it to prevent lag or something?
I would say it's totally possible to increase both the distance and the number of searched pokemon without making it too laggy.

I might be able to help you with something too, feel free to ask me.

**Comment by Charismara** [comment]
> One really useful update that I think would improve this mod a lot is making catchSeries command work for multiple pokemon instead of only one at a time.

Catch series or catch combos (how pixelmon calls it) only work for a single species at the time. See here: https://pixelmonmod.com/wiki/Catch_Combos



> Also, why only 32x32x32 instead of looping all the loaded entities?

This is to prevent lags on low end machines. Updating waypoints takes a lot of time in JourneyMap, especially when there are a lot of them. Feel free to increase that area by increasing the `catchseries.range` config value

**Comment by Ukrayina** [comment]
Yup, I know #catchSeries was meant for catch combos but I think this possible new feature could be really useful for people trying to find multiple pokemon at the same time. Having this specially in the early game and setting it up to find some good pokemon that you will use would be awesome. There was a mod that did this in the past and I remember how helpful it was. I remember using it to find great pokemon at early game but also to find some starters that I liked.
Maybe you could rename it since #catchSeries was meant for catch combos, but having this feature would be great.

Thx for the catchseries.range config tip btw.

**Comment by Charismara** [comment]
feel free to open a Feature Request for that 👍
