### ISSUE TITLE
[Feature Request]: pokeFinder

### ISSUE THREAD

**Issue by Ukrayina** [Charismara/pixelmon-hacks-issues#14]
### Describe the Feature

It should work similarly to #catchSeries, but searching multiple pokemon.

Example:
#pokeFinder add dratini
#pokeFinder add beldum
#pokeFinder start
The feature should search for both dratini and beldum.

Some other useful commands:
#pokeFinder stop (stops without removing the pokemon from the pokeFinder  array)
#pokeFinder clear (clears the array of pokemon and stops)
#pokeFinder remove <pokemon_name> (removes the given pokemon from the pokeFinder  array)
#pokeFinder list (shows all the pokemon in pokeFinder array)

This feature could be really useful when people are trying to find multiple pokemon at the same time. Having this, specially in the early game, and being able to find some good pokemon that you will use would be awesome.
Also, I'm pretty sure you could use the #catchSeries method as a template for it and change a few things since it's quite similar.

**Comment by Charismara** [comment]
Seems nice 👍 good idea

**Comment by Charismara** [comment]
done with `#find` in 2.1.13.0
