### ISSUE TITLE
[Feature Request]: Sound when mega boss spawns

### ISSUE THREAD

**Issue by Pinkashew** [Charismara/pixelmon-hacks-issues#15]
### Describe the Feature

Have a sound when a mega boss also spawns.

**Comment by Charismara** [comment]
creating sounds is kinda hard for me due to the fact, that i got literally no experience in it. I might do new sounds somewhen but nothing is planned for that in the near future

**Comment by Pinkashew** [comment]
Since legendaries and shinies have sounds is it possible to make it so mega bosses just make the same sound?

**Comment by Charismara** [comment]
sure but i would love to keep the sounds unique
