### ISSUE TITLE
[Bug]: autofisher bug

### ISSUE THREAD

**Issue by JaapBonenstaak** [Charismara/pixelmon-hacks-issues#16]
### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Pixelmon Version

9.1.2

### Journeymap Version

5.8.5

### Pixelmon Hacks Version

2.1.12.0

### Describe the bug

When you set the minimum amount of marks to for example 3 and you start fishing and get 1 or 2 marks, it ignores it and continues fishing, but if the server you're playing on is a laggy, the rod occasionally starts rapidly throwing itself into the water for a while before staying in the water. It still works but when someone sees you rapidly throwing the fishing line in the air like that you tend to look a bit stupid and suspicious. It doesnt happen in singleplayer though. Aside from that, great mod.

### To Reproduce

Get on a server with a bit of lag
Go to a spot where you can fish
Set the minimal amount of marks to like 3
Activate the autofisher

**Comment by Charismara** [comment]
that issue is probably due to the way the whole auto fishing thing is coded. I need to rework it
