### ISSUE TITLE
[Question]: Auto catch pokemon and auto look

### ISSUE THREAD

**Issue by Aszuos** [Charismara/pixelmon-hacks-issues#20]
### Question

There is a way to auto enter in battle with pokemons, and specify the pokemon that i want. Or only start to battle with all the pokemons arround?

thanx for the mod, is one of the greatest this i have see after pixelmon <3

**Comment by Charismara** [comment]
Hey, i don't think there is a way to do that without looking super suspicious. Auto Fishing is already a mess :S

**Comment by Charismara** [comment]
closed due to inactivity
