### ISSUE TITLE
[Feature Request]:  Battle list

### ISSUE THREAD

**Issue by D3vilEye** [Charismara/pixelmon-hacks-issues#28]
### Describe the Feature

Hey firstly, thank you for your great work! Well, would be great to have an #battle blacklist list to check which pokés we have added into the filter.

**Comment by Charismara** [comment]
Hey 😄 thank you. 
It seems like you're right and there is no way to check the list again (except exporting it and reading the file which kinda sucks). I'll probably make the `#battle blacklist` command return the whole list in the next update

**Comment by Charismara** [comment]
done in [2.1.15.0](https://www.curseforge.com/minecraft/mc-mods/pixelmon-utilities/files/4439415)
