### ISSUE TITLE
[Bug]: Game crashes suddenly with Auto-Battle option

### ISSUE THREAD

**Issue by TecnoGamer500** [Charismara/pixelmon-hacks-issues#29]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Pixelmon Version

8.3.8

### Journeymap Version

5.7.1

### Pixelmon Hacks Version

1.0.0.10

### Describe the bug

I'm using a macro on my mouse to keep clicking with the right button from time to time on a trainer on a pixelmon server that I play with the auto-battle option turned on. Everything works normally for a considerable time, until the game suddenly crashes. If you can help me solve it I would appreciate it.

### To Reproduce

[crash-2023-03-17_02.28.29-client.txt](https://github.com/Charismara/pixelmon-hacks-issues/files/11000975/crash-2023-03-17_02.28.29-client.txt)

### Crash Report Link

https://mclo.gs/CMeHwNe

**Comment by TecnoGamer500** [comment]
I would be grateful if you could take a look at the crash log and say if there is anything I can do to not crash

**Comment by Charismara** [comment]
1.12.2 is no longer supported. sorry
