### ISSUE TITLE
[Feature Request]: Pause Autobattle when enemy is Shiny, Legendary or an Ultra Beast

### ISSUE THREAD

**Issue by D3vilEye** [Charismara/pixelmon-hacks-issues#31]
### Describe the Feature

Hey! Its possible to stop auto battle if you fish up a shiny mon? Even with shiny finder it kills shinies

**Comment by Charismara** [comment]
i guess that should be possible

**Comment by D3vilEye** [comment]
Maybe something like #battle blacklist #shiny/#legends/#ubs if possible, Thank you!

**Comment by fireblastfr** [comment]
> i guess that should be possible

Would it also be possible to make auto battle stop when it encounters a HA?

**Comment by Charismara** [comment]
> Would it also be possible to make auto battle stop when it encounters a HA?

No. See #3

**Comment by Charismara** [comment]
added in `2.1.17.0`
