### ISSUE TITLE
[Feature Request]: Auto Movement

### ISSUE THREAD

**Issue by bschwar9** [Charismara/pixelmon-hacks-issues#32]
### Describe the Feature

Add an auto run feature. For example I want to fish for bottlecaps but pokemon obviously keep getting encountered. This would be nice as I could set auto run on and auto fish and then come back a few hours later to bottlecaps hopefully.

**Comment by Charismara** [comment]
That sounds like a lot of work for a small benefit. Is there any other reason to write a whole movement system for the player then that?

**Comment by bschwar9** [comment]
Auto run as in escape from battle, sorry for the confusion. I think this would be useful as it would allow you to use the autofish feature for exclusively items if you also had the auto run from battle enabled.

I don't believe this would be hard to implement seeing as you already implemented auto battle.

**Comment by Charismara** [comment]
intelligent player movement is a lot of work for sure and tbh i'm not sure this is worth the effort. I'll keep the issue open and in case this feature get's requested a lot i'll thing about it again.

**Comment by bschwar9** [comment]
Would it be possible to make the repo public? I'd be interested in contributing and adding some features.

**Comment by Charismara** [comment]
I would prefer to keep things as closed as possible. That's why the code is private and licenced with "All rights reserved". No one may modify or reupload anything of this except i gave my permission.

**Comment by fireblastfr** [comment]
> 

Just use auto battle, auto battle selfacknowledge, auto filter on if you gonna farm for bottle caps
