### ISSUE TITLE
[Bug Report]: Proper syntax for #find add pokemon form

### ISSUE THREAD

**Issue by JasonCastle** [Charismara/pixelmon-hacks-issues#34]
### Question

Piggybacking off of [Issue 10](https://github.com/Charismara/pixelmon-hacks-issues/issues/10):

Can't seem to get alternate forms to work; I can't figure out the correct syntax. Can you be more specific for how to use the command? example: " #find add Onix Crystal " doesn't work at all, its just red. I'm seeing other players on [Curseforge](https://www.curseforge.com/minecraft/mc-mods/pixelmon-utilities/comments) ask how to use the command properly as well.

**Comment by Charismara** [comment]
Yeah it seems like one of the latest Pokemon Updates broke the way i'm loading the forms from the Pixelmon.

**Comment by Charismara** [comment]
fixed in 2.1.16.1

**Comment by JasonCastle** [comment]
Not totally fixed yet. Some examples I found: Onix Crystal (the game tries to swap to "Creator form", Magikarp incorrectly identifies "50% form" and "10% form", as well as every letter (Looks like it thinks Magikarp is both an Unknown and a Zygarde?) Magikarp forms should include, for example, Valencian, Skelly, Gray_Bubbles, Apricot_Tiger etc since Magikarp has a lot of actual forms. Eevee doesn't recognize "Spirit" form etc.

I'm finding these forms by locating directly in the Pixelmon jar file, in the "assets\pixlemon\textures\pokemon" location. From there you can navigate individual mon, "all" and then from there I'm not sure exactly what the file structure is.

If there's anything further you need, I'd love to help where I can.
