### ISSUE TITLE
[Feature Request]: Auto acknowledge level up

### ISSUE THREAD

**Issue by bschwar9** [Charismara/pixelmon-hacks-issues#35]
### Describe the Feature

Auto acknowledge level up when using auto battle. 

Have been using autofish + autobattle to grind levels while I am afk/doing something else on my computer, but still have to manually click everytime my poke levels up. Implementing something that auto clicks when your poke levels up would be nice.

**Comment by fireblastfr** [comment]
in the mean time just use a auto clicker thats what ive been doing just search up OP Auto clicker its safe been using it for a while now

**Comment by Charismara** [comment]
done in 2.1.16.2
