### ISSUE TITLE
[Bug]: Game will not launch with  pixelmon-hacks installed under any circumstances 

### ISSUE THREAD

**Issue by WyattTheSkid** [Charismara/pixelmon-hacks-issues#36]
### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Pixelmon Version

9.1.3

### Journeymap Version

5.8.5p6

### Pixelmon Hacks Version

2.1.15.0

### Describe the bug

Originally I believed this to be an incompatibility with some of the other mods I had installed so I tried to launch the game with just pixelmon and journeymap (and pixelmon utils obviously) and it still just crashes after the forge loading screen. I have tried toying witht he versions of pixelmon of the utilities mod of journeymap and I still can't seem to get it to work. Any help would be appreciated thanks.

### To Reproduce

Literally just install mod and dependencies and attempt to launch the game.

### Crash Report Link

https://mclo.gs/zWwsVe9

**Comment by Charismara** [comment]
I cannot reproduce the issue. Have you tried using a different launcher? E.g. CurseForge?

**Comment by Charismara** [comment]
Closed due to inactivity.
