### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JasonCastle** [Charismara/pixelmon-hacks-issues#38]
### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Pixelmon Version

9.1.3

### Journeymap Version

5.8.5p6

### Pixelmon Hacks Version

2.1.16.2

### Describe the bug

[Issue 34](https://github.com/Charismara/pixelmon-hacks-issues/issues/34) Not totally fixed yet. 

Some examples I found: 

- Onix Crystal (the game tries to swap to "Creator form"
- Magikarp incorrectly identifies "50% form" and "10% form", as well as every letter (Looks like it thinks Magikarp is both an Unknown and a Zygarde?) Magikarp forms should include, for example, Valencian, Skelly, Gray_Bubbles, Apricot_Tiger etc since Magikarp has a lot of actual forms. 
- Eevee doesn't recognize "Spirit" form 
- etc.

### To Reproduce

1. Open minecraft
2. Type "#find add " followed by a pixelmon, example Magikarp
3. Press space, optionally try to find a specific form

Expected behavior:
List of valid forms appear which match those found in the Pixlemon files / [documentation](https://pixelmonmod.com/wiki/Form_indices) (not the linked documentation may be incomplete? Probably best to check the actual mod files before implementing)

Actual behavior:
Some pixelmon show no valid forms, just the guide that says "pixelmon [form]" in chat. Some are valid, example Minior seems to show both core and meteor. Some validiate incorrect forms, example Magikarp does not have a 50% form so "#find add Magikarp 50" should *not* be a valid command, but is.

### Extra Notes

I'm finding these forms by locating directly in the Pixelmon jar file, in the "assets\pixlemon\textures\pokemon" location. From there you can navigate individual mon, "all" and then from there I'm not sure exactly what the file structure is. Alternatively, as mentioned above, the [Form Indices](https://pixelmonmod.com/wiki/Form_indices) page might help.

If there's anything further you need, I'd love to help where I can.

**Comment by Charismara** [comment]
The form agurment works by loading all forms of a pokemon by the `specs` in the data. I can't do anything if Pixelmon doesn't add those forms as spec
