### ISSUE TITLE
[Feature Request]: Special Textures added to #find

### ISSUE THREAD

**Issue by Deadman0001** [Charismara/pixelmon-hacks-issues#39]
### Describe the Feature

Hi, I just updated to the newest version of Pixelmon Hacks where the #find command now works with regional forms. I was wondering if this feature could be extended to Special Texture'd Pokemon like Strike form, Alter form, Ashen form, etc.

For reference, these are the special textures that I am referring to: https://pixelmonmod.com/wiki/Special_textures

**Comment by Deadman0001** [comment]
After digging into the configs, it seems that most of the special textures are under the same umbrella of Palettes as shiny Pokemon. If I go into the species config of a Magikarp, the different textures such as Valencian, Skelly, Calico Orange White, etc are under palettes.

**Comment by Charismara** [comment]
seems reasonable. I'll take a look into it.

**Comment by Charismara** [comment]
added in 2.1.16.3
