### ISSUE TITLE
No commands given for some of the new features

### ISSUE THREAD

**Issue by thatirishguyben** [Charismara/pixelmon-hacks-issues#4]
As stated. some of the new features lack in in game command or a command listed on the curseforge mod page

**Comment by Charismara** [comment]
what commands do u got in mind? And for what features?

**Comment by thatirishguyben** [comment]
Looking for the shiny hunt command

**Comment by thatirishguyben** [comment]
![image](https://user-images.githubusercontent.com/121069375/208995946-a7ed6391-75c1-4f06-b293-fce35dbcf412.png)
these are my only options

**Comment by Charismara** [comment]
> Looking for the shiny hunt command

i don't remember any shiny hunt command. There is only a catch series command which places waypoints to a specified pokemon

**Comment by thatirishguyben** [comment]
a shiny hunt command is listed on the curseforge modpage
![image](https://user-images.githubusercontent.com/121069375/209235443-a64c26a2-f6f5-429e-b793-520f8a6a52e3.png)

**Comment by Charismara** [comment]
that change log just says that a `shiny finder` feature is added to the mod (which is just the thing that add waypoints on shiny pokemon)

**Comment by Charismara** [comment]
there is no issue.

please open a feature request if you want some commands for the shiny finder
