### ISSUE TITLE
[Bug]: #find command not working with certain Palettes

### ISSUE THREAD

**Issue by Deadman0001** [Charismara/pixelmon-hacks-issues#40]
### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Pixelmon Version

9.1.3

### Journeymap Version

5.8.5p6

### Pixelmon Hacks Version

2.1.16.3

### Describe the bug

The new #find command is accepting all Palettes as an argument now, however, it is not searching for the Alter Pokemon and some other palettes on Journeymap correctly. 

From my testing, I found the #find command to be working with the following palettes: Strike, Ashen, Valencian, Spirit, Crystal Onix, Karp Feebas, Snow Snorlax, Zombie

Not working: Alter, Creator, Pink, Summer

### To Reproduce

1. Spawn an Alter Bagon via  `/pokespawn Bagon palette:alter`
2. Search for an Alter Bagon via `#find add Bagon Alter`
3. Journeymap was not placing a waypoint at the Alter Bagon.

When you do a general search for Bagon via `#find add Bagon`, both the normal and Alter Bagons show on Journeymap correctly, only when you specify the search for an Alter Bagon does it not search properly.

**Comment by Charismara** [comment]
Thanks for reporting this in that detail. It made fixing it a lot easier and faster.

Fixed in 2.1.16.4
