### ISSUE TITLE
[Bug]: #find command not working with Summer and Creator Palettes

### ISSUE THREAD

**Issue by Deadman0001** [Charismara/pixelmon-hacks-issues#42]
### Minecraft Version

1.16 .5

### Forge Version

36.2.34

### Pixelmon Version

9.1.3

### Journeymap Version

5.8.5p6

### Pixelmon Hacks Version

2.1.16.4

### Describe the bug

This is a follow-up on Issue #40, Alter and Pink palettes are now correctly being searched in the #find command and on Journeymap. However, Summer and Creator palettes are being searched as a form instead of palettes. Images are attached below.

### To Reproduce

1. Spawn a Summer Snorlax via `/pokespawn Snorlax palette:summer`
2. Search for a Summer Snorlax via `#find add Snorlax Summer`
3. Journeymap was not placing a waypoint at the Summer Snorlax.
-
1. Spawn a Creator Eevee via `/pokespawn Eevee palette:creator`
2. Search for a Creator Eevee via `#find add Eevee Creator`
3. Journeymap was not placing a waypoint at the Creator Eevee.

### Extra Notes

![find_summer_creator_form](https://github.com/Charismara/pixelmon-hacks-issues/assets/134663392/ea198a23-8fa3-465f-aecc-8b3d9f175bc1)
![find_valid_palettes](https://github.com/Charismara/pixelmon-hacks-issues/assets/134663392/dcfbb53d-ea4d-4828-b17e-33c56d13593f)

**Comment by Charismara** [comment]
fixed in `2.1.16.5`
