### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fireblastfr** [Charismara/pixelmon-hacks-issues#46]
### Minecraft Version

1.16.5

### Forge Version

32.26.39

### Pixelmon Version

9.13

### Journeymap Version

5.8.5

### Pixelmon Hacks Version

2.1.17.0

### Describe the bug

if you use #battle selfAcknowledge it just keeps disabling it not enabling it

### To Reproduce

^^

**Comment by Charismara** [comment]
fixed in `2.1.17.1`
