### ISSUE TITLE
[Question]:  1.12.2 version?

### ISSUE THREAD

**Issue by Aszuos** [Charismara/pixelmon-hacks-issues#47]
### Question

Hi, i was wondering if have any chance of u be doing a 1.12.2 version. I see that u have already made one , but, cold u make a simpler one and updated? or maybe one with same functions, idk just asking. 

thanks dude, apreciate.

**Comment by D3vilEye** [comment]
Its also possible to do something like an infinite uses Diamond,Silver and Gold Lens by right clicking wild pokémon?

**Comment by Charismara** [comment]
> any chance of u be doing a 1.12.2 version

No, sorry
