### ISSUE TITLE
[Feature Request]: Boss Finder

### ISSUE THREAD

**Issue by Ijeioty** [Charismara/pixelmon-hacks-issues#5]
### Describe the Feature

While the shiny finder does pick up legendary and above bosses you can't find epic or below bosses and I thought it would be a nice future to add.

**Comment by Charismara** [comment]
Makes sense to me but it probably won't happen in this year

**Comment by Ijeioty** [comment]
ok thanks man

**Comment by Charismara** [comment]
done in 2.1.10.0

**Comment by Ijeioty** [comment]
thanks man just dont forget to update your logs
