### ISSUE TITLE
[Feature Request]: Auto Throw

### ISSUE THREAD

**Issue by RisenPharaoh** [Charismara/pixelmon-hacks-issues#51]
### Describe the Feature

To tag along with auto battle, A feature with auto throw, And a option for delay would be cool.

**Comment by Charismara** [comment]
Auto throw?

**Comment by Kiritoking1** [comment]
Like throw the Pokeball at random Pokémon to battle them, just a full autofarm have it run and throw the balls at wild pokes to battle them.

**Comment by Charismara** [comment]
Doing this without looking sus takes too much effort.

wait for #32
