### ISSUE TITLE
Update the 1.12.2 Version

### ISSUE THREAD

**Issue by xJavierR** [Charismara/pixelmon-hacks-issues#56]
### Describe the Feature

Please, 1.12.2 have a lot of players too, im a one of them. :(

**Comment by Charismara** [comment]
i got not time to maintain both versions.

1.16.5 is more than enough

**Comment by xJavierR** [comment]
I understand that point but just the feature of the fishing at less, is so good that feature man :/

**Comment by Leo12th** [comment]
don't need to kee, just put the same off 1.16 pls? i only find 1.12 servers. Begin u.

**Comment by Charismara** [comment]
> don't need to kee, just put the same off 1.16 pls? i only find 1.12 servers. Begin u.

This would need a whole rewrite of 1.12.2. whole rewrite = much work = i don't want that
