### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PetLuck** [Charismara/pixelmon-hacks-issues#61]
### Minecraft Version

1.16.5

### Forge Version

latest

### Pixelmon Version

9.0.8

### Journeymap Version

5.8.5

### Pixelmon Hacks Version

latest

### Describe the bug

auto battle doesn't work, after killing the pokemon it doesn't take the drops so combining it with autofishing won't work as it just stays on the "take all items" menu.

### To Reproduce

enable autobattle
get in a battle

### Extra Notes

you should make it click "drop all drops" or "take all drops" or just make it an option

**Comment by thomit-dev** [comment]
Enable loot filter via #lootfilter.
This will automatically drop any items after battle not in it's whitelist

**Comment by Deadman0001** [comment]
Enable loot filter via #lootfilter.
It'll drop all items after battle that is not within it's whitelist.
