### ISSUE TITLE
[Question]: send src

### ISSUE THREAD

**Issue by PetLuck** [Charismara/pixelmon-hacks-issues#62]
### Question

hello! could you please send me the src for the mod? I am trying to change the modID of the mod and sadly I do not see a way to build the jar file as there's no gradlew. if you could send me a zipfile with the source code of the mod then it would be greatly appreciated <3

**Comment by Charismara** [comment]
This mod is licenced under `All Rights Reserved` which mean you're **NOT** allowed to change anything in my code or application!

Also why would you? There is no need on 1.16 right?
