### ISSUE TITLE
[Question]: do not close this

### ISSUE THREAD

**Issue by PetLuck** [Charismara/pixelmon-hacks-issues#63]
### Question

hey, I need the source code for the mod due to a server I play on banning the MODID of the mod and I'm not able to play with it. if you could maybe send me an edited version of the mod with the modid "fullbright" instead of "pixelmonutils" then it would be great. I have no reason to edit the mod besides that since it is a really good mod and I enjoy using it.

**Comment by Charismara** [comment]
> I need the source code

No, you don't. You are **NOT** permitted to modify anything on my code!

> server I play on banning the MODID of the mod

Which Server and on what Version are you playing on?

> I have no reason to edit the mod besides that since it is a really good mod and I enjoy using it.

Then don't do it. This is the reason why i think about remove this mod from CF and Modrinth and only sell it to people.

**Comment by PetLuck** [comment]
I play on complex pixelmon. version is 1.16.5 and when you join their server it sends a message to all of the admins and they all msg me telling me to remove this mod

**Comment by Charismara** [comment]
Alright i change the mod id now on every update. Updates will be accessable on [my Discord](https://discord.gg/3GtF2QH3q9)
