### ISSUE TITLE
[Bug]: auto fish bug

### ISSUE THREAD

**Issue by jucabalanig** [Charismara/pixelmon-hacks-issues#7]
### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Pixelmon Version

9.1

### Journeymap Version

5.8.5

### Pixelmon Hacks Version

2.1.9

### Describe the bug

auto fisher keep spaming the throw button

### To Reproduce

active auto fisher 
keep spaming throw

**Comment by Charismara** [comment]
Never happend to me but i probably need to rework the auto fish feature anyway

**Comment by Noeble** [comment]
Single player works fine, but when i joined a server it start doing that

**Comment by Charismara** [comment]
more detailed version #16
