### ISSUE TITLE
[Feature Request]:  Ultra Beast Finder

### ISSUE THREAD

**Issue by Trixfinity** [Charismara/pixelmon-hacks-issues#9]
### Describe the Feature

I was in the Ultra Dimension and A Phermosa Spawned right before me, and I instantly killed it with my farfetch'd. I don't want to miss out on another one, in battle, and out.

Can you implement a feature to find Ultra Beasts, not just legendaries?

Same As Legendary Finder, but for Ultra Beasts

**Comment by Charismara** [comment]
Added in 2.1.12.0
